# Generated by Django 2.0.4 on 2019-01-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CT', 'Contributor'), ('ED', 'Editor'), ('UP', 'Upper'), ('CP', 'Copy Contributor'), ('CE', 'Copy Editor')], default='CT', max_length=2),
        ),
    ]
