# Generated by Django 2.0.4 on 2019-01-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
