# Generated by Django 2.0.4 on 2018-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slackId',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CT', 'Contributor'), ('AE', 'Assistant Editor'), ('ED', 'Editor'), ('ST', 'Senior Staff'), ('UP', 'Upper Management')], default='CT', max_length=2),
        ),
    ]
