# Generated by Django 2.0.4 on 2019-02-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_slack_username'),
        ('user_profile', '0002_auto_20190130_2301'),
    ]

    operations = [
    ]
