# Generated by Django 2.0.4 on 2018-11-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20181030_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slackId',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CT', 'Contributor'), ('PM', 'Project Manager'), ('ST', 'Senior Staff'), ('AE', 'Assistant Editor'), ('ED', 'Editor')], default='CT', max_length=2),
        ),
    ]
