# Generated by Django 2.0.4 on 2019-02-20 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_merge_20190205_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='background_color',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='theme',
            new_name='selected_theme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slack_username',
        ),
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_font_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_font_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='tertiary',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
