# Generated by Django 2.0.4 on 2019-02-20 02:25

from django.db import migrations

def add_default_themes(apps, schema_editor):
    # We can't import the Theme model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Theme = apps.get_model('user_profile', 'Theme')

    default_theme = Theme(
        primary="3D73AD",
        secondary="4699DA",
        primary_font_color="FFFFFF",
        secondary_font_color="FFFFFF"
    )
    default_theme.save()

    dark_theme = Theme(
        primary="111111",
        secondary="222222",
        primary_font_color="FFFFFF",
        secondary_font_color="FFFFFF"
    )
    dark_theme.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190219_1825'),
    ]

    operations = [
        migrations.RunPython(add_default_themes)
    ]

