# Generated by Django 2.0.4 on 2019-02-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190219_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tertiary',
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
