# Generated by Django 2.0.4 on 2019-03-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20190219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tertiary',
            field=models.CharField(default='FFFFFF', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_font_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_font_color',
            field=models.CharField(max_length=7),
        ),
    ]
