# Generated by Django 2.0.4 on 2019-03-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20190305_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_theme',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Theme'),
        ),
    ]
