# Generated by Django 2.0.4 on 2019-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20190309_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/chubby.umi/'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(default='https://twitter.com/Cats'),
        ),
    ]
