# Generated by Django 2.0.4 on 2019-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20190326_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.URLField(default=None, null=True),
        ),
    ]
