# Generated by Django 2.2.6 on 2019-11-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20190327_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_font_color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_font_color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tertiary',
            field=models.CharField(max_length=8),
        ),
    ]
