# Generated by Django 2.2.6 on 2019-11-22 16:39

from django.db import migrations

def modify_default_themes(apps, schema_editor):
    # We can't import the Theme model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Theme = apps.get_model('user_profile', 'Theme')
    DailyBruin = Theme.objects.filter(name="Daily Bruin").first()
    DarkBruin = Theme.objects.filter(name="Dark Bruin").first()
    
    DailyBruin.primary =  "#" + DailyBruin.primary
    DailyBruin.secondary =  "#" + DailyBruin.secondary
    DailyBruin.primary_font_color = '#' + DailyBruin.primary_font_color
    DailyBruin.secondary_font_color = '#' + DailyBruin.secondary_font_color
    DailyBruin.tertiary = '#' + DailyBruin.tertiary

    DarkBruin.primary =  "#" + DarkBruin.primary
    DarkBruin.secondary =  "#" + DarkBruin.secondary
    DarkBruin.primary_font_color = '#' + DarkBruin.primary_font_color
    DarkBruin.secondary_font_color = '#' + DarkBruin.secondary_font_color
    DarkBruin.tertiary = '#' + DarkBruin.tertiary
    
    DailyBruin.save()
    DarkBruin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20191122_0837'),
    ]

    operations = [
        migrations.RunPython(modify_default_themes)
    ]
