# Generated by Django 2.2.6 on 2020-01-16 19:16

from django.db import migrations

from django.db import migrations

def modify_default_themes_tertiary_color(apps, schema_editor):
    # We can't import the Theme model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Theme = apps.get_model('user_profile', 'Theme')
    DailyBruin = Theme.objects.filter(name="Daily Bruin").first()
    DarkBruin = Theme.objects.filter(name="Dark Bruin").first()
    
    DailyBruin.tertiary = '#ffe600'
    DarkBruin.tertiary = '#ffe600'
    
    DailyBruin.save()
    DarkBruin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20191214_2055'),
    ]

    operations = [
        migrations.RunPython(modify_default_themes_tertiary_color)
    ]
