# Generated by Django 2.2.6 on 2020-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20200116_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred_themes',
            field=models.ManyToManyField(related_name='starred_themes', to='user_profile.Theme'),
        ),
    ]
