# Generated by Django 2.2.6 on 2020-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_user_starred_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
