# Generated by Django 2.2.6 on 2020-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_theme_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='starred_themes',
            field=models.ManyToManyField(related_name='related_users', to='user_profile.Theme'),
        ),
    ]
