# Generated by Django 2.0.4 on 2018-11-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeowSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('twitter_account_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_account_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_access_key', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_access_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_key', models.CharField(blank=True, help_text="<a target='_blank' href='http://stackoverflow.com/questions/17620266/getting-a-manage-page-access-token-to-upload-events-to-a-facebook-page'>Instructions here</a>", max_length=500, null=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=200, null=True)),
                ('image_selector', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_default_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('shorten_links', models.BooleanField(default=False, help_text='Shorten links using bit.ly?')),
            ],
        ),
        migrations.CreateModel(
            name='SMPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_time', models.TimeField(blank=True, null=True)),
                ('story_url', models.URLField(blank=True, max_length=500, null=True)),
                ('story_short_url', models.URLField(blank=True, max_length=500, null=True)),
                ('featured_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_twitter', models.TextField(blank=True, null=True)),
                ('id_twitter', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('post_facebook', models.TextField(blank=True, null=True)),
                ('post_instagram', models.TextField(blank=True, default='', null=True)),
                ('post_notes', models.TextField(blank=True, default='', null=True)),
                ('id_facebook', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('pub_ready_copy', models.BooleanField(default=False, help_text='Is this copy-edited?')),
                ('pub_ready_online', models.BooleanField(default=False, help_text='Is this ready to send out?')),
                ('sent', models.BooleanField(default=False, help_text='Sent out? This should never be set manually.')),
                ('sending', models.BooleanField(default=False, help_text='Is something currently trying to send this post?')),
                ('sent_time', models.DateTimeField(blank=True, help_text='What time was it actually sent out?', null=True)),
                ('sent_error', models.BooleanField(default=False, help_text='Did the send generate an error?')),
                ('sent_error_text', models.TextField(blank=True, null=True)),
                ('send_now', models.BooleanField(default=False, help_text='Do you want to send this post immediately?')),
            ],
            options={
                'ordering': ['-pub_time'],
                'permissions': (('add_edit_post', 'Can add and edit posts'), ('approve_copy', 'Can mark the post as approved by copy'), ('approve_online', 'Can mark the post as approved by online')),
            },
        ),
    ]
