# Generated by Django 2.0.4 on 2019-01-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
