# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='also_post_to',
            field=models.ForeignKey(blank=True, help_text='This only goes down one level (i.e. no recursion)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='facebook_key',
            field=models.CharField(blank=True, help_text="<a target='_blank' href='http://stackoverflow.com/questions/17620266/getting-a-manage-page-access-token-to-upload-events-to-a-facebook-page'>Instructions here</a>", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='shorten_links',
            field=models.BooleanField(default=False, help_text='Shorten links using bit.ly?'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='pub_ready_copy',
            field=models.BooleanField(default=False, help_text='Is this copy-edited?'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='pub_ready_online',
            field=models.BooleanField(default=False, help_text='Is this ready to send out?'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='sending',
            field=models.BooleanField(default=False, help_text='Is something currently trying to send this post?'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='sent',
            field=models.BooleanField(default=False, help_text='Sent out? This should never be set manually.'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='sent_error',
            field=models.BooleanField(default=False, help_text='Did the send generate an error?'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='sent_time',
            field=models.DateTimeField(blank=True, help_text='What time was it actually sent out?', null=True),
        ),
    ]
