# Generated by Django 2.0.4 on 2019-01-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_section_slack_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='slack_channel',
        ),
    ]
