# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20171109_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='send_now',
            field=models.BooleanField(default=False, help_text='Do you want to send this post immediately?'),
        ),
    ]
