# Generated by Django 2.0.4 on 2019-03-17 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0003_remove_section_slack_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_facebook', models.TextField(blank=True, null=True)),
                ('post_twitter', models.TextField(blank=True, default='', null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('smpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.SMPost')),
            ],
        ),
    ]
