# Generated by Django 2.0.4 on 2018-04-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180427_0323'),
        ('scheduler', '0003_smpost_send_now'),
    ]

    operations = [
    ]
