# Generated by Django 2.0.4 on 2019-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_posthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='post_facebook',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='post_instagram',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
