# Generated by Django 2.0.4 on 2018-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_merge_20180427_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smpost',
            options={'ordering': ['-pub_time'], 'permissions': (('add_edit_post', 'Can add and edit posts'), ('approve_copy', 'Can mark the post as approved by copy'), ('approve_online', 'Can mark the post as approved by online'))},
        ),
        migrations.AddField(
            model_name='smpost',
            name='post_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
