# Generated by Django 2.0.4 on 2019-04-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190326_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, consider mock-deleted.'),
        ),
    ]
