# Generated by Django 2.0.4 on 2019-06-07 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20190606_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='last_edit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
