# Generated by Django 2.0.4 on 2018-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20180429_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smpost',
            options={'ordering': ['-pub_time'], 'permissions': (('add_edit_post', 'Can add and edit posts'), ('approve_copy', 'Can mark the post as approved by copy'), ('approve_online', 'Can mark the post as approved by online'))},
        ),
        migrations.AddField(
            model_name='smpost',
            name='id_facebook',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='smpost',
            name='id_twitter',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
    ]
