# Generated by Django 2.0.4 on 2018-05-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20180524_2309'),
        ('scheduler', '0009_auto_20180511_0809'),
    ]

    operations = [
    ]
