# Generated by Django 2.0.4 on 2019-07-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20190607_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smpost',
            old_name='post_instagram',
            new_name='post_newsletter',
        ),
    ]
