# Generated by Django 2.2.6 on 2020-01-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_posthistory_post_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMPostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('post', models.ManyToManyField(to='scheduler.SMPost')),
            ],
        ),
    ]
