# Generated by Django 2.2.6 on 2020-01-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_smposttag_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smposttag',
            old_name='updated_at',
            new_name='last_touch',
        ),
    ]
