# Generated by Django 2.2.6 on 2020-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20200113_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smposttag',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
