# Generated by Django 2.2.6 on 2020-02-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20200202_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='post_instagram',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
