# Generated by Django 2.2.6 on 2020-10-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_smpost_post_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='version_number',
            field=models.IntegerField(default=0),
        ),
    ]
