# Generated by Django 2.2.6 on 2020-07-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_smpost_post_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='post_facebook_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpost',
            name='post_facebook_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpost',
            name='post_facebook_shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
