# Generated by Django 3.2.21 on 2025-05-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0018_smpost_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='pub_ready_social',
            field=models.BooleanField(default=False, help_text='Is this ready for social?'),
        ),
        migrations.AddField(
            model_name='smpost',
            name='pub_ready_social_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='pub_ready_online',
            field=models.BooleanField(default=False, help_text='Is this ready to publish?'),
        ),
    ]
