# Generated by Django 3.2.21 on 2025-05-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_auto_20250522_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smpost',
            options={'ordering': ['-pub_time'], 'permissions': (('add_edit_post', 'Can add and edit posts'), ('approve_social', 'Can mark the post as approved for social'), ('approve_copy', 'Can mark the post as approved by copy'), ('approve_online', 'Can mark the post as approved by online'))},
        ),
    ]
